apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-backend
  labels:
    app: bms-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bms-backend
  template:
    metadata:
      labels:
        app: bms-backend
    spec:
      containers:
        - name: bms-backend
          image: musaabsami/bms-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: mongodb://mongo-service:27017/your_database
