name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Docker to use Minikube's environment
      run: |
        echo "Switching Docker to Minikube..."
        eval $(minikube docker-env)

    - name: Build Docker image
      run: docker build -t musaabsami/bms-backend:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push musaabsami/bms-backend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f mongo-deployment.yaml
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
