name: Frontend CI/CD

on:
  push:
    paths:
      - 'frontend/**'
      - 'Frontend-deployment.yaml'
      - 'Frontend-service.yaml'
      - '.github/workflows/frontend-deploy.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      IMAGE_NAME: musaabsami/bms-frontend:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Docker with Minikube
        run: eval $(minikube docker-env)

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME ./frontend

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push $IMAGE_NAME

      - name: Deploy to Minikube
        run: |
          kubectl apply -f Frontend-deployment.yaml -n teller-panel
          kubectl apply -f Frontend-service.yaml -n teller-panel
